In [1]:
%pip install pandas
%pip install zipfile
%pip install kaggle

Collecting pandasNote: you may need to restart the kernel to use updated packages.

  Downloading pandas-2.2.3-cp39-cp39-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.0.2-cp39-cp39-win_amd64.whl.metadata (59 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gavin\pythonprojects\aritzia\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\gavin\pythonprojects\aritzia\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp39-cp39-win_amd64.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   -------- ------------------------------- 2.4/11.6 MB 12.2 MB/s eta 0:00:01
   --------------- ------------------------ 4.5/11.6 MB 10.8 MB/s eta 0:00:01
   ----------------------- ---------------- 6.8/11.6 MB 11.0 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.6 MB 13.2 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 13.7 MB/s eta 0:00:00
Downloading numpy-2.0.2-cp39-cp39-win_amd64.whl (15.9 MB)
   ---------------------------------------- 0.0/15.9 MB ? eta -:--:--
   ---------------------- ----------------- 8.9/15.9 MB 42.6 MB/s eta 0:00:01
   ---------------------------------------- 15.9/15.9 MB 43.5 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.2.3 pytz-2024.2 tzdata-2024.2
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement zipfile (from versions: none)
ERROR: No matching distribution found for zipfile

Collecting kaggle
  Downloading kaggle-1.6.17.tar.gz (82 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: six>=1.10 in c:\users\gavin\pythonprojects\aritzia\.venv\lib\site-packages (from kaggle) (1.16.0)
Collecting certifi>=2023.7.22 (from kaggle)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: python-dateutil in c:\users\gavin\pythonprojects\aritzia\.venv\lib\site-packages (from kaggle) (2.9.0.post0)
Collecting requests (from kaggle)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm (from kaggle)
  Downloading tqdm-4.67.0-py3-none-any.whl.metadata (57 kB)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting urllib3 (from kaggle)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting bleach (from kaggle)
  Downloading bleach-6.2.0-py3-none-any.whl.metadata (30 kB)
Collecting webencodings (from bleach->kaggle)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting charset-normalizer<4,>=2 (from requests->kaggle)
  Downloading charset_normalizer-3.4.0-cp39-cp39-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->kaggle)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: colorama in c:\users\gavin\pythonprojects\aritzia\.venv\lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading bleach-6.2.0-py3-none-any.whl (163 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Downloading tqdm-4.67.0-py3-none-any.whl (78 kB)
Downloading charset_normalizer-3.4.0-cp39-cp39-win_amd64.whl (102 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: kaggle
  Building wheel for kaggle (pyproject.toml): started
  Building wheel for kaggle (pyproject.toml): finished with status 'done'
  Created wheel for kaggle: filename=kaggle-1.6.17-py3-none-any.whl size=105796 sha256=802c7c87fa46c93758b3e185e1047076c4f4b135b33563f26e3e8353679dcb95
  Stored in directory: c:\users\gavin\appdata\local\pip\cache\wheels\2b\af\a9\70bffa2773af622d2ebea9c8d407720b86e67bd40c465bf837
Successfully built kaggle
Installing collected packages: webencodings, text-unidecode, urllib3, tqdm, python-slugify, idna, charset-normalizer, certifi, bleach, requests, kaggle
Successfully installed bleach-6.2.0 certifi-2024.8.30 charset-normalizer-3.4.0 idna-3.10 kaggle-1.6.17 python-slugify-8.0.4 requests-2.32.3 text-unidecode-1.3 tqdm-4.67.0 urllib3-2.2.3 webencodings-0.5.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import zipfile

In [8]:
!kaggle datasets download -d "shashwatwork/dataco-smart-supply-chain-for-big-data-analysis"

Dataset URL: https://www.kaggle.com/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis
License(s): CC0-1.0
Downloading dataco-smart-supply-chain-for-big-data-analysis.zip to c:\Users\gavin\PythonProjects\aritzia

  0%|          | 0.00/25.7M [00:00<?, ?B/s]
  4%|▍         | 1.00M/25.7M [00:00<00:03, 6.66MB/s]
 19%|█▉        | 5.00M/25.7M [00:00<00:01, 21.0MB/s]
 39%|███▉      | 10.0M/25.7M [00:00<00:00, 18.8MB/s]
 51%|█████     | 13.0M/25.7M [00:00<00:00, 19.8MB/s]
 70%|███████   | 18.0M/25.7M [00:00<00:00, 26.8MB/s]
 93%|█████████▎| 24.0M/25.7M [00:00<00:00, 34.2MB/s]
100%|██████████| 25.7M/25.7M [00:00<00:00, 27.4MB/s]

In [9]:
zipfile_name = 'dataco-smart-supply-chain-for-big-data-analysis.zip'
with zipfile.ZipFile(zipfile_name, 'r') as file:
    file.extractall()

In [12]:
chain = pd.read_csv("DataCoSupplyChainDataset.csv", encoding="latin1")

In [13]:
chain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [ ]:
chain

In [17]:
chain.to_excel("supply_chain.xlsx", sheet_name='Data')

In [ ]:
%pip install openpyxl

In [18]:
chain

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [ ]:
col1 = chain['order date (DateOrders)']
print(col1)

0          2/3/2018 22:56
1         1/18/2018 12:27
2         1/17/2018 12:06
3         1/16/2018 11:45
4         1/15/2018 11:24
               ...
180514     1/20/2016 3:40
180515     1/19/2016 1:34
180516    1/20/2016 21:00
180517    1/18/2016 20:18
180518    1/19/2016 18:54
Name: shipping date (DateOrders), Length: 180519, dtype: object

In [21]:
chain['shipping date (DateOrders)'] = pd.to_datetime(chain['shipping date (DateOrders)'])

In [22]:
chain['order date (DateOrders)'] = pd.to_datetime(chain['order date (DateOrders)'])

In [23]:
chain['shipping_duration'] = (chain['shipping date (DateOrders)'] - chain['order date (DateOrders)']).dt.days

In [24]:
chain.to_excel("supply_chain_v2.xlsx", sheet_name='Data')

In [25]:
print(chain['Order State'])

0           Java Occidental
1                  Rajastán
2                  Rajastán
3                Queensland
4                Queensland
                ...
180514             Shanghái
180515                Osaka
180516    Australia del Sur
180517    Australia del Sur
180518           Tamil Nadu
Name: Order State, Length: 180519, dtype: object

In [26]:
print(chain.columns.tolist())

['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Image', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode', 'shipping_duration']

In [27]:
latest_date = chain['order date (DateOrders)'].max()
earliest_date = chain['order date (DateOrders)'].min()

print(f"Latest date: {latest_date}")
print(f"Earliest date: {earliest_date}")

Latest date: 2018-01-31 23:38:00
Earliest date: 2015-01-01 00:00:00

In [30]:
print(chain['Shipping Mode'])

0         Standard Class
1         Standard Class
2         Standard Class
3         Standard Class
4         Standard Class
               ...
180514    Standard Class
180515      Second Class
180516    Standard Class
180517    Standard Class
180518    Standard Class
Name: Shipping Mode, Length: 180519, dtype: object

In [33]:
first_class_rows = chain[chain["Shipping Mode"] == "Second Class"]
print(first_class_rows.head(10))

        Type  Days for shipping (real)  Days for shipment (scheduled)  \
8       CASH                         3                              2
10  TRANSFER                         6                              2
11  TRANSFER                         5                              2
12  TRANSFER                         4                              2
16   PAYMENT                         5                              2
22  TRANSFER                         4                              2
23  TRANSFER                         3                              2
24  TRANSFER                         2                              2
25     DEBIT                         6                              2
26  TRANSFER                         5                              2

    Benefit per order  Sales per customer    Delivery Status  \
8          133.720001          278.589996      Late delivery
10         130.580002          272.029999  Shipping canceled
11          45.689999          268.760010      Late delivery
12          21.760000          262.200012      Late delivery
16        -246.360001          321.200012      Late delivery
22          22.370001          298.250000      Late delivery
23          17.700001          294.980011  Shipping canceled
24          90.279999          288.420013  Shipping canceled
25         131.169998          285.140015      Late delivery
26          90.540001          278.589996      Late delivery

    Late_delivery_risk  Category Id   Category Name   Customer City  ...  \
8                    1           73  Sporting Goods          Caguas  ...
10                   0           73  Sporting Goods          Caguas  ...
11                   1           73  Sporting Goods        Freeport  ...
12                   1           73  Sporting Goods         Salinas  ...
16                   1           73  Sporting Goods       Canovanas  ...
22                   1           73  Sporting Goods  Rancho Cordova  ...
23                   0           73  Sporting Goods          Caguas  ...
24                   0           73  Sporting Goods        Billings  ...
25                   1           73  Sporting Goods          Caguas  ...
26                   1           73  Sporting Goods    Wilkes Barre  ...

   Product Card Id Product Category Id Product Description  \
8             1360                  73                 NaN
10            1360                  73                 NaN
11            1360                  73                 NaN
12            1360                  73                 NaN
16            1360                  73                 NaN
22            1360                  73                 NaN
23            1360                  73                 NaN
24            1360                  73                 NaN
25            1360                  73                 NaN
26            1360                  73                 NaN

                                   Product Image  Product Name Product Price  \
8   http://images.acmesports.sports/Smart+watch   Smart watch         327.75
10  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
11  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
12  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
16  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
22  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
23  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
24  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
25  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
26  http://images.acmesports.sports/Smart+watch   Smart watch         327.75

   Product Status shipping date (DateOrders) Shipping Mode  shipping_duration
8               0        2018-01-16 10:00:00  Second Class                  3
10              0        2018-01-19 09:18:00  Second Class                  6
11              0        2018-01-18 08:57:00  Second Class                  5
12              0        2018-01-17 08:36:00  Second Class                  4
16              0        2018-01-18 07:12:00  Second Class                  5
22              0        2018-01-17 05:06:00  Second Class                  4
23              0        2018-01-16 04:45:00  Second Class                  3
24              0        2018-01-15 04:24:00  Second Class                  2
25              0        2018-01-19 04:03:00  Second Class                  6
26              0        2018-01-18 03:42:00  Second Class                  5

[10 rows x 54 columns]